Assigment Problem 8
Name:Akhilesh Karamsetty Venkata Subba
PGID:11810115

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from itertools import combinations
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.svm import LinearSVC

In [2]:
import sys
import warnings
warnings.simplefilter("ignore")

In [3]:
label0 = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/train0.csv")
label1 = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/train1.csv")
label2 = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/train2.csv")
label3 = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/train3.csv")
label4 = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/train4.csv")
label5 = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/train5.csv")
label6 = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/train6.csv")
label7 = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/train7.csv")
label8 = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/train8.csv")
label9 = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/train9.csv")

In [6]:
label0['y'] = 0
label1['y'] = 1
label2['y'] = 2
label3['y'] = 3
label4['y'] = 4
label5['y'] = 5
label6['y'] = 6
label7['y'] = 7
label8['y'] = 8
label9['y'] = 9

In [4]:
label0_t = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/test0.csv")
label1_t = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/test1.csv")
label2_t = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/test2.csv")
label3_t = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/test3.csv")
label4_t = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/test4.csv")
label5_t = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/test5.csv")
label6_t = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/test6.csv")
label7_t = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/test7.csv")
label8_t = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/test8.csv")
label9_t = pd.read_csv("C:/Users/Akhilesh/Downloads/Assignment/MNIST/test9.csv")

In [7]:
label0_t['y'] = 0
label1_t['y'] = 1
label2_t['y'] = 2
label3_t['y'] = 3
label4_t['y'] = 4
label5_t['y'] = 5
label6_t['y'] = 6
label7_t['y'] = 7
label8_t['y'] = 8
label9_t['y'] = 9

In [8]:
train = pd.concat([label0,label1,label2,label3,label4,label5,label6,label7,label8,label9])

In [11]:
train.head(10)

Unnamed: 0   V1   V2   V3   V4   V5   V6   V7   V8   V9  ...  V776  V777  \
0          4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
1          7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
2         12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
3         13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
4         15  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
5         18  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
6         20  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
7         21  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
8         24  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
9         25  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   

   V778  V779  V780  V781  V782  V783  V784  y  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
5   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
6   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
7   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
8   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
9   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  

[10 rows x 786 columns]

In [10]:
test = pd.concat([label0_t,label1_t,label2_t,label3_t,label4_t,label5_t,label6_t,label7_t,label8_t,label9_t])

In [12]:
test.head(10)

Unnamed: 0   V1   V2   V3   V4   V5   V6   V7   V8   V9  ...  V776  V777  \
0          1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
1          2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
2          3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
3          5  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
4          6  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
5          8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
6          9  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
7         10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
8         11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
9         14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   

   V778  V779  V780  V781  V782  V783  V784  y  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
1   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
2   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
3   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
4   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
5   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
6   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
7   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
8   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  
9   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0  

[10 rows x 786 columns]

In [13]:
train[train == np.Inf] = np.NaN
test[test == np.Inf] = np.NaN

In [14]:
train[:] = np.nan_to_num(train)
test[:]=np.nan_to_num(test)

In [16]:
test_nul = test.isna().sum()
train_nul = train.isna().sum()
train_nul.head(10)

Unnamed: 0      4
V1            414
V2            414
V3            414
V4            414
V5            414
V6            414
V7            414
V8            414
V9            414
dtype: int64

In [18]:
train = train.dropna()
test = test.dropna()

In [19]:
dtrain=train.astype(int)
dtest=test.astype(int)

In [20]:
dtrain = dtrain.reset_index(drop=True)
dtest=dtest.reset_index(drop=True)

In [22]:
print(dtrain['y'].value_counts())

1    4084
7    3794
3    3712
2    3601
9    3594
0    3583
6    3580
8    3540
4    3535
5    3263
Name: y, dtype: int64


In [23]:
digit_dlevel = [0]*45
accuracy_train=[0]*45
accuracy_test=[0]*45

In [24]:
SVM_linear=svm.SVC(kernel='linear',max_iter=100)
pair = combinations(np.arange(0,10), 2)
for i,n in zip(list(pair), range(len(accuracy_train))):
        digit_dlevel[n] = i
        d_train = dtrain[dtrain['y'].isin(i)]
        trX= d_train.drop('y', axis = 1)
        trX= trX.div(255.0)
        trY= d_train['y']
        d_test = dtest[dtest['y'].isin(i)]
        teX = dtest.drop('y', axis = 1)
        teX = teX.div(255.0)
        teY = d_test['y']
        SVM.fit(trX, trY)
        accuracy_train[n] = SVM_linear.score(trX, trY) * 100
        accuracy_test[n] = SVM_linear.score(teX, teY) * 100

In [25]:
print (min(accuracy_train),np.argmin(accuracy_train),digit[np.argmin(accuracy_train)])

59.2388306674021 28 (3, 8)


In [29]:
dtrain['y'].replace(to_replace=[3,8],value=10,inplace=True)
dtest['y'].replace(to_replace=[3,8],value=10,inplace=True)
dtrain['y'].unique()

array([ 0,  1,  2, 10,  4,  5,  6,  7,  9], dtype=int64)

In [32]:
digit_layer1=[(0,10),(1,10),(2,10),(4,10),(5,10),(6,10),(7,10),(9,10)]
accuracy_train_1=[0]*8
accuracy_test_1=[0]*8

In [33]:
SVM_linear=svm.SVC(kernel='linear',max_iter=100)
pair = combinations(np.arange(0,10), 2)
for i,n in zip(list(pair), range(len(accuracy_train_1))):
        digit_layer1[n] = i
        d_train = dtrain[dtrain['y'].isin(i)]
        trX= d_train.drop('y', axis = 1)
        trX= trX.div(255.0)
        trY= d_train['y']
        d_test = dtest[dtest['y'].isin(i)]
        teX = dtest.drop('y', axis = 1)
        teX = teX.div(255.0)
        teY = d_test['y']
        SVM.fit(trX, trY)
        accuracy_train_1[n] = SVM_linear.score(trX, trY) * 100
        accuracy_test_1[n] = SVM_linear.score(teX, teY) * 100

In [34]:
print(min(accuracy_train_1),np.argmin(accuracy_train_1),digit_one[np.argmin(accuracy_train_1)])

61.87367678193366 1 (1, 10)


In [35]:
dtrain['y'].replace(to_replace=[1,10],value=11,inplace=True)
dtest['y'].replace(to_replace=[1,10],value=11,inplace=True)
dtrain['y'].unique()

array([ 0, 11,  2,  4,  5,  6,  7,  9], dtype=int64)

In [36]:
digit_layer2=[(0,11),(2,11),(4,11),(5,11),(6,11),(7,11),(9,11)]
accuracy_train_2=[0]*7
accuracy_test_2=[0]*7

In [37]:
SVM_linear=svm.SVC(kernel='linear',max_iter=100)
pair = combinations(np.arange(0,10), 2)
for i,n in zip(list(pair), range(len(accuracy_train_2))):
        digit_layer2[n] = i
        d_train = dtrain[dtrain['y'].isin(i)]
        trX= d_train.drop('y', axis = 1)
        trX= trX.div(255.0)
        trY= d_train['y']
        d_test = dtest[dtest['y'].isin(i)]
        teX = dtest.drop('y', axis = 1)
        teX = teX.div(255.0)
        teY = d_test['y']
        SVM.fit(trX, trY)
        accuracy_train_2[n] = SVM_linear.score(trX, trY) * 100
        accuracy_test_2[n] = SVM_linear.score(teX, teY) * 100

In [38]:
print(min(accuracy_train_2),np.argmin(accuracy_train_2),digit_two[np.argmin(accuracy_train_2)])

58.52580839526009 1 (2, 11)


In [39]:
dtrain['y'].replace(to_replace=[2,11],value=12,inplace=True)
dtest['y'].replace(to_replace=[2,11],value=12,inplace=True)
dtrain['y'].unique()

array([ 0, 12,  4,  5,  6,  7,  9], dtype=int64)

In [40]:
digit_layer3=[(0,12),(4,12),(5,12),(6,12),(7,12),(9,12)]
accuracy_train_3=[0]*6
accuracy_test_3=[0]*6

In [41]:
SVM_linear=svm.SVC(kernel='linear',max_iter=100)
pair = combinations(np.arange(0,10), 2)
for i,n in zip(list(pair), range(len(accuracy_train_3))):
        digit_layer_3[n] = i
        d_train = dtrain[dtrain['y'].isin(i)]
        trX= d_train.drop('y', axis = 1)
        trX= trX.div(255.0)
        trY= d_train['y']
        d_test = dtest[dtest['y'].isin(i)]
        teX = dtest.drop('y', axis = 1)
        teX = teX.div(255.0)
        teY = d_test['y']
        SVM.fit(trX, trY)
        accuracy_train_3[n] = SVM_linear.score(trX, trY) * 100
        accuracy_test_3[n] = SVM_linear.score(teX, teY) * 100

In [42]:
print(min(accuracy_train_3),np.argmin(accuracy_train_3),digit_three[np.argmin(accuracy_train_3)])

66.6043956043956 2 (5, 12)


In [43]:
dtrain['y'].replace(to_replace=[5,12],value=13,inplace=True)
dtest['y'].replace(to_replace=[5,12],value=13,inplace=True)
dtrain['y'].unique()

array([ 0, 13,  4,  6,  7,  9], dtype=int64)

In [44]:
digit_layer_4=[(0,13),(4,13),(6,13),(7,13),(9,13)]
accuracy_train_4=[0]*5
accuracy_test_4=[0]*5

In [45]:
SVM_linear=svm.SVC(kernel='linear',max_iter=100)
pair = combinations(np.arange(0,10), 2)
for i,n in zip(list(pair), range(len(accuracy_train_4))):
        digit_layer_4[n] = i
        d_train = dtrain[dtrain['y'].isin(i)]
        trX= d_train.drop('y', axis = 1)
        trX= trX.div(255.0)
        trY= d_train['y']
        d_test = dtest[dtest['y'].isin(i)]
        teX = dtest.drop('y', axis = 1)
        teX = teX.div(255.0)
        teY = d_test['y']
        SVM.fit(trX, trY)
        accuracy_train_4[n] = SVM_linear.score(trX, trY) * 100
        accuracy_test_4[n] = SVM_linear.score(teX, teY) * 100

In [46]:
print(min(accuracy_train_4),np.argmin(accuracy_train_4),digit_four[np.argmin(accuracy_train_4)])

62.50795671546785 3 (7, 13)


In [47]:
dtrain['y'].replace(to_replace=[7,13],value=14,inplace=True)
dtest['y'].replace(to_replace=[7,13],value=14,inplace=True)
dtrain['y'].unique()

array([ 0, 14,  4,  6,  9], dtype=int64)

In [48]:
digit_layer_5=[(0,14),(4,14),(6,14),(9,14)]
accuracy_train_5=[0]*4
accuracy_test_5=[0]*4

In [49]:
SVM_linear=svm.SVC(kernel='linear',max_iter=100)
pair = combinations(np.arange(0,10), 2)
for i,n in zip(list(pair), range(len(accuracy_train_5))):
        digit_dlevel_5[n] = i
        d_train = dtrain[dtrain['y'].isin(i)]
        trX= d_train.drop('y', axis = 1)
        trX= trX.div(255.0)
        trY= d_train['y']
        d_test = dtest[dtest['y'].isin(i)]
        teX = dtest.drop('y', axis = 1)
        teX = teX.div(255.0)
        teY = d_test['y']
        SVM.fit(trX, trY)
        accuracy_train_5[n] = SVM_linear.score(trX, trY) * 100
        accuracy_test_5[n] = SVM_linear.score(teX, teY) * 100

In [50]:
print(min(accuracy_test_5),np.argmin(accuracy_test_5),digit_five[np.argmin(accuracy_test_5)])

55.572924808503984 3 (9, 14)


In [51]:
dtrain['y'].replace(to_replace=[9,14],value=15,inplace=True)
dtest['y'].replace(to_replace=[9,14],value=15,inplace=True)
dtrain['y'].unique()

array([ 0, 15,  4,  6], dtype=int64)

In [52]:
digit_layer_6=[(0,15),(4,15),(6,15)]
accuracy_train_6=[0]*3
accuracy_test_6=[0]*3

In [53]:
SVM_linear=svm.SVC(kernel='linear',max_iter=100)
pair = combinations(np.arange(0,10), 2)
for i,n in zip(list(pair), range(len(accuracy_train_6))):
        digit_layer_6[n] = i
        d_train = dtrain[dtrain['y'].isin(i)]
        trX= d_train.drop('y', axis = 1)
        trX= trX.div(255.0)
        trY= d_train['y']
        d_test = dtest[dtest['y'].isin(i)]
        teX = dtest.drop('y', axis = 1)
        teX = teX.div(255.0)
        teY = d_test['y']
        SVM.fit(trX, trY)
        accuracy_train_6[n] = SVM_linear.score(trX, trY) * 100
        accuracy_train_6[n] = SVM_linear.score(teX, teY) * 100

In [54]:
print(min(accuracy_train_6),np.argmin(accuracy_train_6),digit_six[np.argmin(accuracy_train_6)])

64.27909212649796 1 (4, 15)


In [55]:
dtrain['y'].replace(to_replace=[4,15],value=16,inplace=True)
dtest['y'].replace(to_replace=[4,15],value=16,inplace=True)
dtrain['y'].unique()

array([ 0, 16,  6], dtype=int64)

In [56]:
digit_layer_7=[(0,16),(6,16)]
accuracy_train_7=[0]*2
accuracy_test_7=[0]*2

In [57]:
SVM_linear=svm.SVC(kernel='linear',max_iter=100)
pair = combinations(np.arange(0,10), 2)
for i,n in zip(list(pair), range(len(accuracy_train_7))):
        digit_layer_7[n] = i
        d_train = dtrain[dtrain['y'].isin(i)]
        trX= d_train.drop('y', axis = 1)
        trX= trX.div(255.0)
        trY= d_train['y']
        d_test = dtest[dtest['y'].isin(i)]
        teX = dtest.drop('y', axis = 1)
        teX = teX.div(255.0)
        teY = d_test['y']
        SVM.fit(trX, trY)
        accuracy_train_7[n] = SVM_linear.score(trX, trY) * 100
        accuracy_train_7[n] = SVM_linear.score(teX, teY) * 100

In [58]:
print(min(accuracy_train_7),np.argmin(accuracy_train_7),digit_seven[np.argmin(accuracy_train_7)])

70.52563984955509 1 (6, 16)


In [60]:
dtrain['y'].replace(to_replace=[6,16],value=17,inplace=True)
dtest['y'].replace(to_replace=[6,16],value=17,inplace=True)
dtrain['y'].unique()

array([ 0, 17], dtype=int64)

In [61]:
digit_layer_8=[(0,17)]
accuracy_train_8=[0]
accuracy_test_8=[0]

In [62]:
SVM_linear=svm.SVC(kernel='linear',max_iter=100)
pair = combinations(np.arange(0,10), 2)
for i,n in zip(list(pair), range(len(accuracy_train_8))):
        digit_dlevel[n] = i
        d_train = dtrain[dtrain['y'].isin(i)]
        trX= d_train.drop('y', axis = 1)
        trX= trX.div(255.0)
        trY= d_train['y']
        d_test = dtest[dtest['y'].isin(i)]
        teX = dtest.drop('y', axis = 1)
        teX = teX.div(255.0)
        teY = d_test['y']
        SVM.fit(trX, trY)
        accuracy_train_8[n] = SVM_linear.score(trX, trY) * 100
        accuracy_test_8[n] = SVM_linear.score(teX, teY) * 100

In [63]:
print(min(accuracy_train_8),np.argmin(accuracy_train_8),digit_seven[np.argmin(accuracy_train_8)])

90.88904811773135 0 (0, 16)


In [64]:
print(Accuracy_Training_eight,Accuracy_Test_eight)

[90.88904811773135] [90.9125411149532]


In [67]:
Test_Acc = []
Test_Acc.append(min(accuracy_test))
Test_Acc.append(min(accuracy_test_1))
Test_Acc.append(min(accuracy_test_2))
Test_Acc.append(min(accuracy_test_3))
Test_Acc.append(min(accuracy_test_4))
Test_Acc.append(min(accuracy_test_5))
Test_Acc.append(min(accuracy_test_6))
Test_Acc.append(min(accuracy_test_7))
Test_Acc.append(min(accuracy_test_8))

In [65]:
First_iter = []
First_iter.append(digit[np.argmin(accuracy_train)])
First_iter.append(digit_one[np.argmin(accuracy_train_1)])
First_iter.append(digit_two[np.argmin(accuracy_train_2)])
First_iter.append(digit_three[np.argmin(accuracy_train_3)])
First_iter.append(digit_four[np.argmin(accuracy_train_4)])                  
First_iter.append(digit_five[np.argmin(accuracy_train_5)])
First_iter.append(digit_six[np.argmin(accuracy_train_6)])
First_iter.append(digit_seven[np.argmin(accuracy_train_7)])
First_iter.append(digit_eight[np.argmin(accuracy_train_8)])

In [66]:
Training_Acc = []
Training_Acc.append(min(accuracy_train))
Training_Acc.append(min(accuracy_train_1))
Training_Acc.append(min(accuracy_train_2))
Training_Acc.append(min(accuracy_train_3))
Training_Acc.append(min(accuracy_train_4))
Training_Acc.append(min(accuracy_train_5))
Training_Acc.append(min(accuracy_train_6))
Training_Acc.append(min(accuracy_train_7))
Training_Acc.append(min(accuracy_train_8))

In [68]:
I=[10,11,12,13,14,15,16,17,18]

In [69]:
SVC=pd.DataFrame()
SVC['First_iter'] = First_iter
SVC['Imputed_Value']=I
SVC['Training_Acc']=Training_Acc
SVC['Test_Acc']=Test_Acc
SVC

First_iter  Imputed_Value  Training_Acc   Test_Acc
0     (3, 8)             10     59.238831  11.748334
1    (1, 10)             11     61.873677  19.397824
2    (2, 11)             12     58.525808  24.622586
3    (5, 12)             13     66.604396  33.166062
4    (7, 13)             14     62.507957  38.753479
5    (9, 14)             15     55.572925  40.178797
6    (4, 15)             16     64.279092  53.314498
7    (6, 16)             17     70.525640  63.759804
8    (0, 17)             18     90.889048  90.912541